# Generated by Django 3.0.7 on 2020-06-17 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200617_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='ordered',
        ),
    ]
