# Generated by Django 3.0.7 on 2020-06-19 14:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200617_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 19, 14, 14, 45, 287815, tzinfo=utc)),
        ),
    ]
