# Generated by Django 3.0.7 on 2020-06-19 14:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200619_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 19, 14, 51, 25, 347830, tzinfo=utc)),
        ),
    ]
