# Generated by Django 3.0.7 on 2020-06-20 13:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200619_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 20, 13, 44, 16, 877306, tzinfo=utc)),
        ),
    ]
